"""
Django settings for website_1 project.

Generated by 'django-admin startproject' using Django 3.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'n()+o0$vx9*1x6-vir@g6!pojc=$i@je5%84wymok)i5+$8*&_'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['127.0.0.1']

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'apps.cms',
    'apps.news',
    'apps.xfzauth',
    'apps.ueditor',
    'rest_framework',
    'debug_toolbar'
]

MIDDLEWARE = [
    'debug_toolbar.middleware.DebugToolbarMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'website_1.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',

        # 设置templates路径
        'DIRS': [os.path.join(BASE_DIR, 'front', 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
            # 配置模板的static标签
            'builtins': [
                'django.templatetags.static'
            ]
        },
    },
]

WSGI_APPLICATION = 'website_1.wsgi.application'

# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'website',
        'USER': 'root',
        'PASSWORD': 'Shengao:1.82M',
        'HOST': '127.0.0.1',
        'PORT': '3306',
    }
}

# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

AUTH_USER_MODEL = 'xfzauth.User'

# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

# 缓存配置
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.memcached.MemcachedCache',
        'LOCATION': '127.0.0.1:11211',
    }
}

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/

STATIC_URL = '/static/'

# 配置静态文件路径
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'front', 'dist')
]
STATIC_ROOT = os.path.join(BASE_DIR, 'static_dist')

# 配置上传图片路径
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# 配置富文本编辑器UEditor

# 配置上传到七牛云：
# Qiniu云配置
QINIU_ACCESS_KEY = 'SyhwHaV41gC9UlDmSlerJX94SMWPNd0oZUWx-uGH'
QINIU_SECRET_KEY = '05mfgW_DlQLENbIZcz10qc1nPyI2HCoUSueMTBuQ'
QINIU_BUCKET_NAME = 'gexuejy'
QINIU_DOMAIN = 'www.gexuejy.com'

# UEditor配置
UEDITOR_UPLOAD_TO_QINIU = True
UEDITOR_QINIU_ACCESS_KEY = QINIU_ACCESS_KEY
UEDITOR_QINIU_SECRET_KEY = QINIU_SECRET_KEY
UEDITOR_QINIU_BUCKET_NAME = QINIU_BUCKET_NAME
UEDITOR_QINIU_DOMAIN = QINIU_DOMAIN

# 配置上传到自身服务器：
UEDITOR_UPLOAD_TO_SERVER = True
UEDITOR_UPLOAD_PATH = MEDIA_ROOT
UEDITOR_CONFIG_PATH = os.path.join(BASE_DIR, 'front', 'dist', 'ueditor', 'config.json')

# 'X-Frame-Options' to 'deny'报错处理
# 原文网址：https://blog.csdn.net/ora_dy/article/details/104984482?tdsourcetag=s_pctim_aiomsg
X_FRAME_OPTIONS = 'SAMEORIGIN'

# 配置首页一次加载多少篇文章
ONE_PAGE_NEWS_COUNT = 2

# Django-Debug-Toolbar相关的配置
INTERNAL_IPS = ['127.0.0.1']
DEBUG_TOOLBAR_PANELS = [
    # 代表是哪个Django版本
    'debug_toolbar.panels.versions.VersionsPanel',

    # 用来计时的，判断加载当前页面总共花的时间
    'debug_toolbar.panels.timer.TimerPanel',

    # 读取Django中的配置信息
    'debug_toolbar.panels.settings.SettingsPanel',

    # 看到当前请求头喝响应头信息
    'debug_toolbar.panels.headers.HeadersPanel',

    # 当前请求的信息（视图函数，Cookie信息，Session信息等）
    'debug_toolbar.panels.request.RequestPanel',

    # 查看SQL语句
    'debug_toolbar.panels.sql.SQLPanel',

    # 查看加载的静态文件
    'debug_toolbar.panels.staticfiles.StaticFilesPanel',

    # 查看模板文件
    'debug_toolbar.panels.templates.TemplatesPanel',

    # 查看缓存
    'debug_toolbar.panels.cache.CachePanel',

    # 查看信号
    'debug_toolbar.panels.signals.SignalsPanel',

    # 查看日志
    'debug_toolbar.panels.logging.LoggingPanel',

    # 重定向
    'debug_toolbar.panels.redirects.RedirectsPanel'
]

DEBUG_TOOLBAR_CONFIG = {
    'JQUERY_URL': ''
}
